### ISSUE TITLE
Update Connect-M365Tenant to reflect the new MS requirement pnp connection

### ISSUE THREAD

**Issue by githubths** [System-Admins/m365assessment#12]
Hi System Admins,

First of all, thank you for your great work.

please update the Connect-M365Tenant Module by the new requirement to have a own pnp AppID for access Sharepoint Data via Powershell. 

Suggestion: 
Line 24
```
[Parameter(Mandatory=$true)]
    [string]
    $SharepointAppID
```
 
Line 195
`$null = Connect-PnPOnline -AzureEnvironment Production -Interactive -Url $spoUrls.AdminUrl -WarningAction SilentlyContinue -ErrorAction Stop -ClientId $SharepointAppID;`

**Comment by System-Admins-ath** [comment]
Hi @githubths,
Thanks you the kind words.
But what requirement are you referring to (can you provide a link)? :-)

**Comment by githubths** [comment]
Yes sure,

https://pnp.github.io/blog/post/changes-pnp-management-shell-registration/

After September 9, it is no longer possible to access the sharepoint via Powershell without registering your own app. Microsoft has deleted the Multitenant app.

Kind Regards
Steve

**Comment by System-Admins-ath** [comment]
Thank you. I will test and implement it when I have some spare time.
