### ISSUE TITLE
Report never generates

### ISSUE THREAD

**Issue by screwlooseit** [System-Admins/m365assessment#14]
Once the assessment completes i get the following:

Generating report, please wait for a few seconds
Exception: xxxxxxx\Documents\PowerShell\Modules\SystemAdmins.M365Assessment\1.0.12\private\helper\m365\api\Invoke-MsAdminApi.ps1:76
Line |
  76 |              throw ("Could not call API, the exception is '{0}'" -f $_ …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not call API, the exception is 'The custom error module does not recognize this error.'

**Comment by System-Admins-ath** [comment]
I know that Microsoft have some issues. But I will check it tomorrow :-)

**Comment by screwlooseit** [comment]
i also get an error at the start of the Invoke 

ConvertFrom-SecureString: xxxx\PowerShell\Modules\SystemAdmins.M365Assessment\1.0.12\private\helper\connection\Test-M365Connection.ps1:63
Line |
  63 |  … Action SilentlyContinue -ErrorAction Stop | ConvertFrom-SecureString;
     |                                                ~~~~~~~~~~~~~~~~~~~~~~~~
     | The input object cannot be bound to any parameters for the command either because the command does not take
     | pipeline input or the input and its properties do not match any of the parameters that take pipeline input.

**Comment by System-Admins-ath** [comment]
1. Update to new module version 1.0.13
2. Close PowerShell session and re-open
3. Import module and try again.
